glzr-io/glazewm

GlazeWM.Bar/MainWindow.xaml.cs
GlazeWM.Bootstrapper/Startup.cs
GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/Monitors/CommandHandlers/RefreshMonitorStateHandler.cs
GlazeWM.Domain/Monitors/CommandHandlers/RemoveMonitorHandler.cs
GlazeWM.Domain/Monitors/Commands/RefreshMonitorStateCommand.cs
GlazeWM.Domain/Monitors/Commands/RemoveMonitorCommand.cs
GlazeWM.Domain/Monitors/EventHandlers/DisplaySettingsChangedHandler.cs
GlazeWM.Domain/Monitors/Events/NewMonitorDetectedEvent.cs
GlazeWM.Domain/Monitors/Events/WorkingAreaResizedEvent.cs
GlazeWM.Domain/Windows/EventHandlers/WindowDestroyedHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowHiddenHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowLocationChangedHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowShownHandler.cs
GlazeWM.Domain/Windows/WindowService.cs
GlazeWM.Infrastructure/WindowsApi/Enums/EventConstant.cs
GlazeWM.Infrastructure/WindowsApi/Events/WindowLocationChangedEvent.cs
GlazeWM.Infrastructure/WindowsApi/WindowEventService.cs

* Listen for positioning changes to appbar windows (eg. the Windows taskbar). Reposition bar window and resize the monitor's working area on any such changes.

feat: handle app bar changes

---

GlazeWM.Bootstrapper/Program.cs
GlazeWM.Bootstrapper/Startup.cs
GlazeWM.Domain/UserConfigs/BarComponentConfigConverter.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/EvaluateUserConfigHandler.cs
GlazeWM.Infrastructure/Bussing/Bus.cs
GlazeWM.Infrastructure/Yaml/YamlDeserializationService.cs

* Move centralized error handling from `Bus` to `Startup` class.
* Improve error messages when deserializing user config.
* Fix crash if containing directory for user config file didn't already exist.

feat: improve user config error handling

---

GlazeWM.Bar/BarViewModel.cs
GlazeWM.Bar/MainWindow.xaml.cs
GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/UserConfigs/BarConfig.cs
GlazeWM.Domain/UserConfigs/BarPosition.cs
GlazeWM.Domain/Workspaces/Workspace.cs

Hello!
I've just stumbled upon your lovely project and wanted to implement some helpful features for me.
Hope that's ok to open a couple PR for those (If not please tell me and I'll not submit others)!
---
This is the first one which just adds a bar config option to switch it between top/position.

feat: Bar position

---

GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs
GlazeWM.Domain/Windows/CommandHandlers/SetMaximizedHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/SetMinimizedHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/ToggleMaximizedHandler.cs
GlazeWM.Domain/Windows/Commands/SetMaximizedCommand.cs
GlazeWM.Domain/Windows/Commands/SetMinimizedCommand.cs
GlazeWM.Domain/Windows/Commands/ToggleMaximizedCommand.cs
GlazeWM.Infrastructure/WindowsApi/WindowsApiService.cs

* Add "set minimized" command for minimizing the focused window.
* Add "set maximized" command for maximizing the focused window.
* Add "toggle maximized" command for toggling maximized state of the focused window.

feat: set minimized and maximized commands

---

GlazeWM.Domain/Monitors/CommandHandlers/RemoveMonitorHandler.cs
GlazeWM.Domain/Workspaces/CommandHandlers/FocusWorkspaceHandler.cs
GlazeWM.Domain/Workspaces/Workspace.cs

I found a todo in the code, and thought I'd create a PR for it.

feat: Workspace keep alive based on user config

---

GlazeWM.Domain/Common/CommandHandlers/ExecProcessHandler.cs
GlazeWM.Domain/Common/Commands/StartProcessCommand.cs
GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs

* Rename `start` command string to `exec`.

refactor(domain): rename `start` command to `exec`

---

GlazeWM.Bar/BarViewModel.cs
GlazeWM.Bar/Components/ComponentPortal.xaml
GlazeWM.Bar/Components/TextComponent.xaml
GlazeWM.Bar/Components/TextComponent.xaml.cs
GlazeWM.Bar/Components/TextComponentViewModel.cs
GlazeWM.Domain/UserConfigs/BarComponentConfigConverter.cs
GlazeWM.Domain/UserConfigs/TextComponentConfig.cs

Hi!
Just like the title says, i made a non-clickable text component (based on clock component).
Although it was a simple task, i'm sure there's room for improvements since i'm not a C# dev 😅

Added non-clickable text component

---

GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/ReloadUserConfigHandler.cs
GlazeWM.Domain/UserConfigs/UserConfigService.cs
GlazeWM.Domain/Windows/CommandHandlers/AddWindowHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/RunWindowRulesHandler.cs
GlazeWM.Domain/Windows/Commands/RunWindowRulesCommand.cs

* Create `RunWindowRulesCommand` to avoid duplicate code in `AddWindowHandler` and `ReloadUserConfigHandler`.

refactor: separate command for running window rules

---

GlazeWM.Bar/Components/TextComponent.xaml
GlazeWM.Bar/Components/TextComponentViewModel.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/EvaluateUserConfigHandler.cs
GlazeWM.Domain/UserConfigs/TextComponentConfig.cs

* Add config properties `left_click_command` and `right_click_command` to be able to invoke a command via text bar component.

feat: invoke commands on click in text bar component

---

README.md

Added reference to text component in README to address #164

Update README to add text component (#164)

---

GlazeWM.Domain/Common/Enums/Sequence.cs
GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs
GlazeWM.Domain/Workspaces/CommandHandlers/FocusWorkspaceSequenceHandler.cs
GlazeWM.Domain/Workspaces/Commands/FocusWorkspaceSequenceCommand.cs

feat: add commands "focus workspace next/prev" (#155)

---

GlazeWM.Domain/Common/Utils/Keywords.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/EvaluateUserConfigHandler.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs

Prevent use command parts at workspaces names (#161)

---

GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs
GlazeWM.Domain/Windows/CommandHandlers/SetTilingHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/ToggleFloatingHandler.cs
GlazeWM.Domain/Windows/Commands/SetTilingCommand.cs

* Add new command "set tiling" for changing a window's state to be tiling (similar to "set floating", "set minimized", etc.).

feat: add "set tiling" command

---

GlazeWM.Bar/BarViewModel.cs
GlazeWM.Bar/Components/BindingModeComponent.xaml
GlazeWM.Bar/Components/BindingModeComponent.xaml.cs
GlazeWM.Bar/Components/BindingModeComponentViewModel.cs
GlazeWM.Bar/Components/ComponentPortal.xaml
GlazeWM.Bar/Components/ComponentViewModel.cs
GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/Common/CommandHandlers/SetBindingModeHandler.cs
GlazeWM.Domain/Common/Events/BindingModeChangedEvent.cs
GlazeWM.Domain/Containers/ContainerService.cs
GlazeWM.Domain/UserConfigs/BarComponentConfigConverter.cs
GlazeWM.Domain/UserConfigs/BindingModeComponentConfig.cs

* Add new bar component for showing the currently active binding mode.
* Add binding mode bar component to sample config.

feat: binding mode bar component

---

GlazeWM.Bar/BarViewModel.cs
GlazeWM.Bar/Components/ComponentPortal.xaml
GlazeWM.Bar/Components/TilingDirectionComponent.xaml
GlazeWM.Bar/Components/TilingDirectionComponent.xaml.cs
GlazeWM.Bar/Components/TilingDirectionComponentViewModel.cs
GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/Containers/CommandHandlers/ChangeContainerLayoutHandler.cs
GlazeWM.Domain/Containers/ContainerService.cs
GlazeWM.Domain/Containers/Events/LayoutChangedEvent.cs
GlazeWM.Domain/UserConfigs/BarComponentConfigConverter.cs
GlazeWM.Domain/UserConfigs/TilingDirectionComponentConfig.cs

* Add new bar component for showing the current tiling direction (referred to as "layout" throughout codebase currently).
* Add tiling direction bar component to sample config.

feat: tiling direction bar component

---

GlazeWM.Bar/Components/ClockComponentViewModel.cs
GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/UserConfigs/ClockComponentConfig.cs
README.md

Pull request to show calendar week in clock component (#196).

feat(bar): calendar week in clock component

---

GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/Containers/CommandHandlers/RedrawContainersHandler.cs
GlazeWM.Domain/UserConfigs/GeneralConfig.cs
GlazeWM.Domain/UserConfigs/UserConfig.cs
GlazeWM.Domain/UserConfigs/UserConfigService.cs
GlazeWM.Infrastructure/WindowsApi/WindowsApiService.cs

* Be able to show floating windows as always on top via new config option `general.show_floating_on_top: true|false`.

feat: show floating on top

---

GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/UserConfigs/GeneralConfig.cs
GlazeWM.Domain/UserConfigs/UserConfig.cs

* Disable `show_floating_on_top`  and `cursor_follows_focus` by default.

feat: disable `show_floating_on_top` and `cursor_follows_focus` by default

---

GlazeWM.Bar/Components/WindowTitleComponentViewModel.cs

* Truncate window title to 60 chars in window title component.

feat: truncate window title in bar component

---

README.md

Add more new bar components to the readme

chore: update bar component configuration readme

---

GlazeWM.Bootstrapper/Program.cs
GlazeWM.Infrastructure/Bussing/Bus.cs
GlazeWM.Infrastructure/Common/CommandHandlers/HandleFatalExceptionHandler.cs

* Add last 15 command invocations to error logs.

feat: add command history to error logs

---

README.md

Also added `tiling direction toggle` to the command list

Update README to add instructions for installing via Winget

---

README.md

docs: add Scoop installation instructions

---

README.md

docs: add "focus_border_color" to readme

---

GlazeWM.Domain/Workspaces/CommandHandlers/FocusWorkspaceHandler.cs

@Petar0000 mentions [two issues](https://github.com/lars-berger/GlazeWM/pull/274#issuecomment-1507028934) with PR #274 that this PR fixes.

Fix workspace toggle

---

GlazeWM.Domain/Containers/CommandHandlers/RedrawContainersHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowFocusedHandler.cs

fix: handle focus events from windows on hidden workspaces

---

GlazeWM.App.IpcServer/IpcMessageHandler.cs

* Fix issue where `subscribe -e all` would bypass restrictions on which events can be subscribed to.
* Fix issue where event subscriptions weren't getting removed on ws disconnect.

fix: `subscribe -e all` respects subscribable events

---

GlazeWM.Infrastructure/WindowsApi/CpuStatsService.cs
GlazeWM.Infrastructure/WindowsApi/MemoryStatsService.cs

fix: resolve cpu and memory component crash

---

GlazeWM.App/GlazeWM.App.csproj
GlazeWM.Domain/UserConfigs/NetworkComponentConfig.cs
GlazeWM.Domain/UserConfigs/SystemTrayComponentConfig.cs
GlazeWM.Domain/UserConfigs/VolumeComponentConfig.cs

* Fix icon font showing up as squares in bar.

fix: embedded icon font not displaying correctly

---

GlazeWM.Bar/Components/ComponentPortal.xaml

* Add missing background/padding to volume component.

fix: volume component background and padding

---

GlazeWM.Domain/Containers/CommandHandlers/RedrawContainersHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowLocationChangedHandler.cs

fix: maximized windows redrawing on wrong monitor

---

GlazeWM.App.IpcServer/IpcMessageHandler.cs

fix: redraw and assign focus after ipc commands

---

README.md

Added a notice for the V3 update, including direct links to the Discord server and the Tracker. Let me know if anything else needs changed.

docs: add V3 overhaul notice to README

---

Cargo.lock
packages/wm/Cargo.toml
packages/wm/src/containers/container.rs
packages/wm/src/containers/traits/common_getters.rs
packages/wm/src/containers/traits/position_getters.rs
packages/wm/src/containers/traits/tiling_direction_getters.rs
packages/wm/src/containers/traits/tiling_size_getters.rs
packages/wm/src/windows/traits/window_getters.rs

Enum_dispatch is great but creates bug with the IDE.
I'am trying other crates, looking for a better one

refactor: replace `enum_dispatch` with `ambassador` for better code completion

---

.github/workflows/package.yaml
packages/wm/src/common/platform/native_window.rs

feat: set foreground window without simulating keypress

---

README.md

This document the newly added support for Winget

docs: Add Winget to readme

---

packages/wm/src/common/platform/native_window.rs

* Fetching the process name errored for some windows which caused them to be unmanaged.
Closes #701

fix: fetch process name with less privileges

---

packages/wm/src/common/platform/event_window.rs

* Sometimes caused workspaces to get swapped between monitors.
Closes #723

fix: ignore display change messages when resuming from sleep

---

.github/workflows/winget-release.yaml

As said above, the missing 'v' stops from finding the url

ci: fix regex for detecting latest version in Winget release workflow

---

packages/wm/src/common/platform/event_window.rs

fix: ignore programmatic mouse inputs with focus follows cursor

---

packages/wm/src/common/events/handle_window_location_changed.rs

Fixes regression introduced in #834

fix: regression in detecting when a window is restored from fullscreen

---

packages/wm/src/common/rect.rs

fix: fix regression where some taskbar positions cause incorrect working area

---

packages/wm/src/common/events/handle_window_location_changed.rs

fix: prevent window flicker when toggling between fullscreen states

---

packages/wm/src/common/platform/event_window.rs
packages/wm/src/common/platform/native_window.rs

fix: fix `focus_follows_cursor` on touchpads

---

packages/wm/src/windows/commands/update_window_state.rs
packages/wm/src/windows/insertion_target.rs
packages/wm/src/windows/mod.rs
packages/wm/src/windows/non_tiling_window.rs
packages/wm/src/windows/tiling_window.rs

feat: restore to previous tiling size from minimized/fullscreen

---

.github/workflows/lint-check.yaml
.github/workflows/package.yaml
.github/workflows/winget-release.yaml

ci: enable lint check on opened PR's

---

.github/workflows/winget-release.yaml

Updated the workflow to a new commit version and changed the username to match the username that is currently being used. Should reduce potential errors in the future.

ci: updated to newer winget release workflow

---

packages/wm-common/src/parsed_config.rs

feat: improve handling of missing fields in config

---

packages/wm/src/commands/general/platform_sync.rs
packages/wm/src/commands/general/toggle_pause.rs
packages/wm/src/events/handle_window_moved_or_resized_end.rs
packages/wm/src/events/handle_window_moved_or_resized_start.rs
packages/wm/src/main.rs
packages/wm/src/wm.rs
packages/wm/src/wm_state.rs

fix: prevent commands from still being run during pause state

---

packages/wm-platform/src/platform.rs
packages/wm/src/commands/general/platform_sync.rs
packages/wm/src/commands/window/move_window_in_direction.rs
packages/wm/src/commands/window/move_window_to_workspace.rs
packages/wm/src/commands/window/update_window_state.rs
packages/wm/src/events/handle_window_focused.rs
packages/wm/src/pending_sync.rs
packages/wm/src/wm_state.rs

feat: consistent window z-order on focus and startup

---

packages/wm-platform/src/com.rs
packages/wm-platform/src/native_window.rs
packages/wm/src/commands/general/platform_sync.rs

feat: ensure windows overlap the taskbar when fullscreen

---

README.md

This PR adds the Chocolatey and Scoop package managers to the README and changes the wording in the instructions for installing with Winget.
The source code of the Chocolatey package is available here: https://github.com/rudesome/chocolateypackage-glazewm
And for the Scoop package: https://github.com/ScoopInstaller/Extras/blob/master/bucket/glazewm.json

docs: add chocolatey and scoop install to README

---

packages/wm-common/src/app_command.rs
packages/wm/src/wm.rs

feat: add `--workspace-in-direction` to `move` command

---

packages/wm/src/commands/general/platform_sync.rs
packages/wm/src/commands/window/update_window_state.rs
packages/wm/src/ipc_server.rs
packages/wm/src/main.rs

fix: `channel closed` error and improvements to error handling
