LarsWM.Bar/BarManagerService.cs
LarsWM.Bar/MainWindow.xaml
LarsWM.Bar/MainWindow.xaml.cs
LarsWM.Bootstrapper/Program.cs
LarsWM.Domain/Containers/CommandHandlers/RedrawContainersHandler.cs
LarsWM.Domain/Monitors/Monitor.cs
LarsWM.Domain/Monitors/MonitorService.cs
LarsWM.Domain/Windows/Window.cs
LarsWM.Domain/Windows/WindowService.cs
LarsWM.Domain/Workspaces/Workspace.cs
LarsWM.Infrastructure/WindowsApi/WindowsApiService.cs

* Scale window width and height up/down if there's a mismatch in the DPI of the monitor and the DPI of the window.
* Set process DPI awareness to `PerMonitorAwareV2`.
* Handle DPI scaling of the bar window. Use `MoveWindow` to manually size and position the WPF window.

feat: dpi awareness

---

GlazeWM.Bar/Components/WorkspacesComponent.xaml
GlazeWM.Domain/Workspaces/Workspace.cs

Since the config property already existed but wasn't bound to the UI this was quite a basic change.

feat: Custom workspace display names

---

GlazeWM.Bootstrapper/Startup.cs
GlazeWM.Infrastructure/Bussing/Bus.cs

* Change error log path to `C:\Users\<YOUR_USER>\.glaze-wm\errors.log`. Previously error logs were stored in the directory of the `.exe` file, which is unintuitive. Also, if in the future, the application is installed in the "Program Files" directory, the error logs become increasingly difficult to access.
* Attempt cleanup and show all windows (regardless of their displayed workspace) on fatal errors.

feat: improve behavior on crash

---

GlazeWM.Bootstrapper/sample-config.yaml

> includes some optional commented examples in the sample config that are like that of the README.md, with the inclusion of dialog boxes from https://github.com/lars-berger/GlazeWM/issues/58

feat: add some default window rules to sample config

---

GlazeWM.Domain/Windows/WindowService.cs

* Avoid managing windows that are likely to be application menu windows (eg. Notepad++ autocomplete popup and title bar menu in Keepass). These windows are identified by having an owner window and no `WS_CAPTION` window style.
Closes #61 and #57

feat: avoid managing menu windows

---

GlazeWM.Domain/Windows/CommandHandlers/AddWindowHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/ToggleFloatingHandler.cs
GlazeWM.Domain/Workspaces/CommandHandlers/MoveFocusedWindowToWorkspaceHandler.cs

* When the WM is launched, retain minimized windows in their minimized state (instead of restoring them to be tiling). 
Closes #56

feat: respect initial minimized state

---

GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs
GlazeWM.Domain/Windows/CommandHandlers/SetFloatingHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/SetFocusedWindowFloatingHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/ToggleFloatingHandler.cs
GlazeWM.Domain/Windows/Commands/SetFloatingCommand.cs
GlazeWM.Domain/Windows/Commands/SetFocusedWindowFloatingCommand.cs

* Previously, there was only a "toggle floating" command to set a window to be floating. This adds a new command, "set floating", that sets a window to be floating regardless of its current state.

feat: add separate "set floating" command

---

GlazeWM.Bar/BarViewModel.cs
GlazeWM.Bar/Components/ClockComponent.xaml
GlazeWM.Bar/Components/ComponentViewModel.cs
GlazeWM.Bar/Components/WorkspacesComponent.xaml
GlazeWM.Bar/MainWindow.xaml
GlazeWM.Domain/UserConfigs/BarComponentConfig.cs
GlazeWM.Domain/UserConfigs/BarConfig.cs

I've added the ability to set the font weight via config.  Defaults to `Normal`.
Possible values are as per https://docs.microsoft.com/en-us/dotnet/api/system.windows.fontweights?view=windowsdesktop-6.0#remarks

feat: Add ability to set the font weight

---

GlazeWM.Domain/Windows/Window.cs

When I open a windows terminal instance using Windows -> Run, GlazeWM crashes.
I've found in the `errors.log` file:
```
21/06/2022 8:56:32 am
Object reference not set to an instance of an object.   at GlazeWM.Domain.Windows.Window.get_ProcessName() in C:\Projects.GitHub\GlazeWM\GlazeWM.Domain\Windows\Window.cs:line 43
at GlazeWM.Domain.UserConfigs.UserConfigService.<>c__DisplayClass9_0.<GetMatchingWindowRules>b__0(WindowRuleConfig rule) in C:\Projects.GitHub\GlazeWM\GlazeWM.Domain\UserConfigs\UserConfigService.cs:line 136
at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource …
```

bug: When opening windows terminal, GlazeWM sometimes crashes

---

GlazeWM.Infrastructure/WindowsApi/KeybindingService.cs

This resolves the issue where a keybind has less keys than the keys that were pressed.
E.g. when you have a keybind of `Alt+1`, but you press `Control+Alt+1`, it still fired.  It should NOT fire it, because you didn't press exactly `Alt+1`.
I had a problem where I have `Control+Alt+1` bound in another application and Glaze hijacked the keybinding, despite my config only being `Alt+1`.
Let me know if this is fine, or if there is a better way to handle this.
Cheers,

bug: Added code to make sure that the keys pressed matches the keybind exactly

---

GlazeWM.Domain/Containers/CommandHandlers/AttachAndResizeContainerHandler.cs
GlazeWM.Domain/Containers/Container.cs
GlazeWM.Domain/Windows/CommandHandlers/ResizeWindowHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowMovedOrResizedHandler.cs
README.md

* Be able to drag the sizing border of a window to resize a window. If a window is the only container in a workspace, this snaps the window back to its original position.

feat: resize windows with sizing border

---

GlazeWM.Domain/Windows/CommandHandlers/ResizeWindowHandler.cs

* Prevent containers from exceeding min/max size percentage.
* Fix issue where pixel scale factor was calculated incorrectly when window had floating siblings.

fix: prevent containers from exceeding min/max size percentage

---

GlazeWM.Domain/Monitors/CommandHandlers/AddMonitorHandler.cs
GlazeWM.Domain/Monitors/MonitorService.cs
GlazeWM.Domain/UserConfigs/WorkspaceConfig.cs
GlazeWM.Domain/Workspaces/CommandHandlers/FocusWorkspaceHandler.cs
GlazeWM.Domain/Workspaces/CommandHandlers/MoveWindowToWorkspaceHandler.cs
GlazeWM.Domain/Workspaces/WorkspaceService.cs

This is the only PR im not 100% happy with as the DisplayNames are quite generic (e.g. `\\.\DISPLAY1`).
Ideally in my opinion, it'd be cool to have the actual monitor names as usable strings on the config. I've googled around a bit and apparently it's quite hard to figure that out, so I haven't tried to implement that.

feat: bind workspaces to specific monitors

---

GlazeWM.Bootstrapper/Program.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/EvaluateUserConfigHandler.cs
GlazeWM.Domain/UserConfigs/UserConfigService.cs

Hey!
@stewart-james asked in #41 for allowing to load a different config file, so I quickly threw together this PR. 
`new FileInfo(path).FullName` is a good replacement for the URI thing as that allows relative file paths as well.

feat: Allow change of config file location via command line args

---

GlazeWM.Bar/Components/WorkspacesComponent.xaml

Hey there!
This is a very quick fix which should fix #115:

bug: Fix #115 - Workspace name missalignment

---

GlazeWM.Domain/Common/CommandHandlers/ExecProcessHandler.cs
GlazeWM.Domain/Common/Commands/StartProcessCommand.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs

* Avoid formatting `exec` command to lowercase (since the arguments passed to the process might be case sensitive).
* Prevent crash if there is an error when launching a process via `exec` (eg. if the executable is not found). Instead show a pop-up with the message.
* Allow paths to executables with spaces by wrapping the file path in single quotes (eg. `exec 'C:\Program Files\Git\git-bash.exe'`.
* Expand environment variables when calling `exec` with a file path (eg. `exec %ProgramFiles%\Git\git-bash.exe`).

feat: improvements to `exec` command

---

README.md

Hey! 
I added the `--config` command line argument and the  `bind_to_monitor` thing to the readme.
Additionally, I added all the commands in the readme as well and think that's a good thing to have. (Since I think there are some undocumented ones right now, like the `start` one.)
I'm not sure if you'd also want to add a little description to every command, if so, you'd need to help me with that please!

Added some missing features to the readme

---

GlazeWM.Bootstrapper/Startup.cs
GlazeWM.Domain/JsonContainerConverter.cs
GlazeWM.Infrastructure/Bussing/Bus.cs
GlazeWM.Infrastructure/Serialization/JsonElementExtensions.cs

* Serialize container state to JSON and append it to the error log file on fatal exceptions.
* Fix issue where fatal exceptions might occur before `ApplicationExitingEvent` subscription, preventing cleanup.
* Add more detailed stacktrace to fatal exceptions.

feat: improve error logging

---

GlazeWM.Bar/BarService.cs
GlazeWM.Bootstrapper/Program.cs
GlazeWM.Bootstrapper/Startup.cs
GlazeWM.Domain/Common/CommandHandlers/ExecProcessHandler.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs
GlazeWM.Infrastructure/Bussing/Bus.cs
GlazeWM.Infrastructure/Common/CommandHandlers/ExitApplicationHandler.cs
GlazeWM.Infrastructure/Common/Commands/ExitApplicationCommand.cs
GlazeWM.Infrastructure/DependencyInjection.cs
GlazeWM.Infrastructure/Exceptions/ExceptionHandler.cs
GlazeWM.Infrastructure/Exceptions/ExceptionHandlerOptions.cs
GlazeWM.Infrastructure/WindowsApi/KeybindingService.cs
GlazeWM.Infrastructure/WindowsApi/SystemTrayService.cs
GlazeWM.Infrastructure/WindowsApi/WindowEventService.cs

* Create a new `ExceptionHandler` class for handling fatal/non-fatal exceptions consistently. 
* Wrap each thread in a try-catch with exceptions handled by `ExceptionHandler`.
* Avoid spawning new threads (and message pumps) for the `KeybindingService`, `SystemTrayService`, and `WindowEventService`. This means these services now rely on the main thread message pump.
* Show message prompt with error on all fatal exceptions.

refactor: global exception handling

---

GlazeWM.Domain/Containers/CommandHandlers/AttachContainerHandler.cs
GlazeWM.Domain/Containers/CommandHandlers/ReplaceContainerHandler.cs
GlazeWM.Domain/Containers/Container.cs
GlazeWM.Domain/Containers/ContainerService.cs
GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/RegisterKeybindingsHandler.cs
GlazeWM.Domain/UserConfigs/CommandParsingService.cs
GlazeWM.Domain/Windows/CommandHandlers/AddWindowHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/IgnoreWindowHandler.cs
GlazeWM.Domain/Windows/Commands/IgnoreWindowCommand.cs
GlazeWM.Domain/Windows/WindowService.cs

* Add "ignore" command for unmanaging a window and preventing keybindings from firing when the window has focus. Previously, there wasn't actually an actual "ignore" command - instead there was a specific check if "ignore" was present in window rules (and the window would not be managed if it was present).
* Change check when a keybinding is triggered to look up whether an ignored window currently has focus.

fix: keybindings do not fire if desktop has focus

---

GlazeWM.Domain/Containers/CommandHandlers/AttachAndResizeContainerHandler.cs
GlazeWM.Domain/Containers/CommandHandlers/FocusInDirectionHandler.cs
GlazeWM.Domain/Containers/CommandHandlers/ToggleFocusModeHandler.cs
GlazeWM.Domain/Containers/Container.cs
GlazeWM.Domain/Containers/ContainerService.cs
GlazeWM.Domain/Windows/CommandHandlers/MoveWindowHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/ResizeWindowHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/ToggleFloatingHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowMinimizeEndedHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowMovedOrResizedHandler.cs
GlazeWM.Domain/Workspaces/CommandHandlers/MoveWindowToWorkspaceHandler.cs

* Change Container methods that get a container of specific type. Change from format: `container.ChildrenOfType(typeof(IResizable))` -> `container.ChildrenOfType<IResizable>()`.
* rename `GetNextSiblingOfType` and `GetPreviousSiblingOfType` to exclude `Get`.

refactor: change container methods for getting a container of a specific type

---

GlazeWM.Domain/UserConfigs/CommandHandlers/RegisterKeybindingsHandler.cs
GlazeWM.Infrastructure/Bussing/Bus.cs
GlazeWM.Infrastructure/WindowsApi/SystemEventService.cs
GlazeWM.Infrastructure/WindowsApi/WindowEventService.cs

Keybinding hooks, window event hooks, and system event hooks all run on the main thread after the changes in #130. To ensure that state changes are synchronous, there's a lock statement in the `Bus.Invoke` and `Bus.RaiseEvent` methods. However, since these hooks are all now on the same thread, the lock statement no longer takes effect and events/commands would be invoked while another event/command is being processed. This caused issues with the `move to workspace <NAME>` command (ref #137).
* To get the lock statement working again in `Bus`, add new `Bus` methods for invoking commands & raising events on a new thread.

fix: out of order commands & events

---

GlazeWM.Domain/Containers/ContainerService.cs
GlazeWM.Domain/Windows/CommandHandlers/UnmanageWindowHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowFocusedHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowMinimizedHandler.cs
GlazeWM.Domain/Workspaces/CommandHandlers/FocusWorkspaceHandler.cs

* Remove `ContainerService.PendingFocusContainer`. Reassign focus after window close by calling `SetNativeFocusCommand` asynchronously. This ensure that focus gets corrected *after* the OS initially sets focus.

refactor: remove `PendingFocusContainer`; simplify how focus is set after window close

---

GlazeWM.Domain/Containers/Container.cs
GlazeWM.Domain/Windows/CommandHandlers/UnmanageWindowHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowMinimizedHandler.cs
GlazeWM.Domain/Windows/WindowService.cs
GlazeWM.Domain/Workspaces/CommandHandlers/FocusWorkspaceHandler.cs
GlazeWM.Domain/Workspaces/CommandHandlers/MoveWindowToWorkspaceHandler.cs

* Add a consistent way of getting the window to reassign focus to after a window is unmanaged, minimized, or moved to another workspace.

fix: focus reassignment after window removal

---

GlazeWM.Domain/Containers/Container.cs
GlazeWM.Domain/Containers/ContainerService.cs
GlazeWM.Domain/Containers/RootContainer.cs
GlazeWM.Domain/Containers/SplitContainer.cs
GlazeWM.Domain/Monitors/Monitor.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/RegisterKeybindingsHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/RunWindowRulesHandler.cs
GlazeWM.Domain/Windows/Window.cs
GlazeWM.Domain/Windows/WindowService.cs
GlazeWM.Domain/Workspaces/Workspace.cs

* When running multiple commands via window rules or keybindings, the subject container might point to an old reference (eg. when going from a tiling to a floating window). To avoid this, refetch the subject container between each command invocation in a window rule or keybinding.
* Add new `Id` property to all containers. 
Closes #149 and #144.

fix: invalid reference when running multiple commands

---

GlazeWM.Domain/Containers/CommandHandlers/AttachAndResizeContainerHandler.cs
GlazeWM.Domain/Containers/CommandHandlers/ChangeContainerLayoutHandler.cs
GlazeWM.Domain/Containers/CommandHandlers/DetachAndResizeContainerHandler.cs
GlazeWM.Domain/Containers/CommandHandlers/ResizeContainerHandler.cs
GlazeWM.Domain/Containers/Commands/ResizeContainerCommand.cs
GlazeWM.Domain/DependencyInjection.cs
GlazeWM.Domain/Windows/CommandHandlers/ResizeWindowHandler.cs

* Previously when attaching a tiling window, all sibling windows would be resized by the same amount. This could cause a sibling window to have a negative `SizePercentage`. After the change, siblings are resized when attaching by a factor of their previous `SizePercentage`.

fix: prevent overflow when attaching a new tiling window

---

GlazeWM.Domain/Windows/CommandHandlers/RunWindowRulesHandler.cs

* Fix crash where window rules are run after a window has been ignored (eg. `["ignore", "set floating"]`)

fix: invalid reference after ignore window rule

---

GlazeWM.Bar/BarService.cs
GlazeWM.Bar/BarViewModel.cs
GlazeWM.Bar/Components/ComponentViewModel.cs
GlazeWM.Bar/Components/WorkspacesComponentViewModel.cs
GlazeWM.Bar/XamlHelper.cs
GlazeWM.Domain/UserConfigs/BarComponentConfig.cs
GlazeWM.Domain/UserConfigs/WorkspacesComponentConfig.cs

* Allow transparency for color properties in the bar config to be set via RGBA instead of ARGB (since it's a far more common color format).
* Change default background colors for bar components to be transparent.

feat: bar transparency via RGBA

---

GlazeWM.Bar/BarViewModel.cs
GlazeWM.Bar/Components/ComponentViewModel.cs
GlazeWM.Bar/MainWindow.xaml.cs
GlazeWM.Bar/XamlHelper.cs
GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/UserConfigs/BarConfig.cs
GlazeWM.Domain/Workspaces/Workspace.cs

* Some properties in the config can be specified as <AMOUNT>px, whereas others have to be specified as <AMOUNT>. Change most properties so that they can either be written as `<AMOUNT>` or `<AMOUNT>px`. `gaps.inner_gap` and `gaps.outer_gap` still need to be defined without `px` affix.

feat: improve consistency of units in config

---

GlazeWM.Bar/Components/BatteryComponentViewModel.cs

Just a quick fix for consistency :)

fix(bar): use battery label format for systems without a battery

---

GlazeWM.Bar/Components/BatteryComponentViewModel.cs
GlazeWM.Bar/Components/TilingDirectionComponentViewModel.cs
GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/UserConfigs/BatteryComponentConfig.cs
GlazeWM.Domain/UserConfigs/TilingDirectionComponentConfig.cs
README.md

* Improve consistency of label properties in the config. Rename them to be in the format of `label_{condition}`.

feat: rename bar label properties

---

GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/UserConfigs/CommandParsingService.cs

* Rename "toggle focus mode" -> "focus mode toggle".
* Fix incorrect "tiling direction toggle" naming.

feat: rename "toggle focus mode" -> "focus mode toggle"

---

GlazeWM.Bootstrapper/sample-config.yaml
GlazeWM.Domain/UserConfigs/BarComponentSeparatorConfig.cs

* Fix fallback to default `label` if others are not provided.
* Temporarily remove `component_separator` from default config until issue with binding mode component is solved.

fix: fallback to default label for component separators

---

GlazeWM.Domain/Containers/CommandHandlers/MoveContainerWithinTreeHandler.cs
GlazeWM.Domain/Containers/CommandHandlers/SetNativeFocusHandler.cs

* Fixes crash described in #236.
Closes #236.

fix: remove calls to `CenterCursorOnRectCommand`

---

GlazeWM.Domain/UserConfigs/CommandHandlers/EvaluateUserConfigHandler.cs

On first launch, after answering Yes to creating a sample file, the following exception was being thrown:
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at GlazeWM.Domain.UserConfigs.CommandHandlers.EvaluateUserConfigHandler.Handle(EvaluateUserConfigCommand command) in C:\source\github\GlazeWM\GlazeWM.Domain\UserConfigs\CommandHandlers\EvaluateUserConfigHandler.cs:line 57
>    at GlazeWM.Infrastructure.Bussing.Bus.Invoke[T](T command) in C:\source\github\GlazeWM\GlazeWM.Infrastructure\Bussing\Bus.cs:line 41
>    at GlazeWM.Domain.Common.CommandHandlers.PopulateInitialStateHandler.Handle(PopulateInitialStateCommand command) in C:\source\github\GlazeWM\GlazeWM.Domain\Common\CommandHandlers\PopulateInitialStateHandler.cs:line 38
>    at …

fix: exception when creating `sample-config.yaml`

---

GlazeWM.Bar/Components/ComponentPortal.xaml
GlazeWM.Bar/Components/ComponentViewModel.cs
GlazeWM.Bar/MainWindow.xaml
GlazeWM.Domain/UserConfigs/BarComponentConfig.cs

Hi,
There are two parts this pull request: 
- rounded corners for bar components
- a fix to the bar component border
If you want me to split these to 2 different PRs let me know.
The changes to the bar fix the background overflowing the border. Here is the before and after: 
I have also added the possibility of adding rounded corners to bar components. With this I have a small problem. For some components there is a 1 pixel line that is transparent for some reason: 
If you have any ideas how to fix that or any other recommendations let me know. 
Joonatan

feat: add border radius option for bar components

---

GlazeWM.Domain/UserConfigs/CommandHandlers/RegisterKeybindingsHandler.cs
GlazeWM.Infrastructure/Common/CommandHandlers/HandleFatalExceptionHandler.cs

* Add prompt option to continue without exiting on fatal exceptions.
* Ensure `FatalExceptionHandler` is called on exceptions within keybinding handlers.

feat: improvements to fatal exception handling

---

GlazeWM.Bootstrapper/Resources/sample-config.yaml
GlazeWM.Domain/UserConfigs/GeneralConfig.cs
GlazeWM.Domain/Workspaces/CommandHandlers/FocusWorkspaceHandler.cs
README.md

Added a configuration option to enable automatic back-and-forth (as in [i3wm](https://i3wm.org/docs/userguide.html#workspace_auto_back_and_forth))
With this configuration enabled the previous workspace will be focused when switching to the current workspace.
See also #151

feat: add option to toggle workspace on refocus

---

GlazeWM.Bar/Components/BatteryComponent.xaml
GlazeWM.Bar/Components/BatteryComponentViewModel.cs
GlazeWM.Bar/Components/LabelComponent.xaml
GlazeWM.Bar/Components/LabelComponent.xaml.cs
GlazeWM.Bar/Components/LabelSpan.cs
GlazeWM.Bar/Components/LabelViewModel.cs
GlazeWM.Bar/XamlHelper.cs

* Allows mixing of foreground, background, font family, font weight, and font size, within a label.
* Supported attributes:
* Foreground: `ff`
* Background: `bg`
* Font family: `ff`
* Font weight: `fw`
* Font size: `fs`
Example:
```yaml
components_right:
- type: "battery"
label_draining: <attr ff="Arial">{battery_level}</attr>%
label_charging: {battery_level}<attr fg="blue">%</attr>
label_power_saver: <attr ff="Arial" fg="blue">{battery_level}%</attr>
```

feat: parse bar component labels

---

GlazeWM.Domain/UserConfigs/CommandParsingService.cs
GlazeWM.Domain/UserConfigs/GapsConfig.cs
GlazeWM.Domain/Workspaces/Workspace.cs
README.md

* Added support for specifying individual outer gaps (top, right, bottom, left)
* Also tested that this change is backwards compatible with existing config (i.e. `outer_gap: 20` still works)
closes: #276

feat: add shorthand syntax to outer gaps

---

GlazeWM.Infrastructure/Utils/KeybindingHelper.cs

Tiny PR here. 
I grabbed some low-hanging fruit from the "Free to take" list. https://github.com/users/lars-berger/projects/2/views/1?pane=issue&itemId=28116872
I chose to implement this with a switch so that more keybinding aliasing could be done quickly in future (e.g. Meta -> Alt)
Ignore the completely overwritten first commit, I decided as I was drafting this PR that it'd be better to check against the Enum first before moving on to the switch so there's not a whole bunch of unnecessary comparisons.

feat: alias Ctrl to Control

---

GlazeWM.Bar/BarViewModel.cs
GlazeWM.Bar/MainWindow.xaml
GlazeWM.Domain/UserConfigs/BarConfig.cs
README.md

Allows setting `show_bar_as_overlay: true` which makes the bar appear on top
This, coupled with #282 should address #340 
preview:

feat: Allow setting bar as overlay

---

GlazeWM.Bar/Components/VolumeComponentViewModel.cs

I was unable to compile the solution after some PRs were merged over the last few days. Looks like one of the methods is now expecting a `Dictionary<string, Func<string>>` instead of `Dictionary<string, string>`

fix: compilation error in `VolumeComponentViewModel`

---

GlazeWM.Infrastructure/WindowsApi/WindowsApiService.cs

* stderror is correctly output when built for release.

fix: stderror is correctly output when built for release

---

GlazeWM.Domain/Containers/CommandHandlers/RedrawContainersHandler.cs
GlazeWM.Domain/Containers/Container.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/RegisterKeybindingsHandler.cs
GlazeWM.Domain/UserConfigs/CommandHandlers/RunWithSubjectContainerHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/SetFloatingHandler.cs
GlazeWM.Domain/Windows/CommandHandlers/SetTilingHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowFocusedHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowMinimizeEndedHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowMinimizedHandler.cs
GlazeWM.Domain/Workspaces/CommandHandlers/MoveWindowToWorkspaceHandler.cs

* Update container ID when the `Container` type changes (eg. `TilingWindow` -> `FloatingWindow`). This fixes the issue with window rules not being ran.
* Revert the changes from #366 (caused issues when moving windows between workspaces).

fix: update id when the `Container` type changes

---

GlazeWM.Domain/Containers/CommandHandlers/RedrawContainersHandler.cs

* Fix issue where detached windows might be redrawn due to the latest redraw changes in #388 .

fix: fatal exception on redraw of detached window

---

GlazeWM.Domain/Containers/CommandHandlers/RedrawContainersHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowLocationChangedHandler.cs
GlazeWM.Domain/Windows/EventHandlers/WindowMinimizeEndedHandler.cs
GlazeWM.Domain/Windows/MaximizedWindow.cs
GlazeWM.Domain/Windows/WindowService.cs

when new windows are created and after switching worskpaces
Known issue currently: when a new window is spawned, it appears above the maximized window ✅ but when it closes, the next tiling/floating window gets focused ❌

feat: maximized windows stay maximized

---

GlazeWM.Domain/Workspaces/Workspace.cs

Fix workspace size and Y position when using `offsetY` bar config option with bar on the bottom

fix: correct workspace size with Y offset and bar on bottom

---

README.md

I added a guide on how to remap `LWin + <somekey>` to use with GlazeWM.
Feel free to move this out of the README.md if it takes up too much space

docs: add readme section for using `LWin` keybindings

---

GlazeWM.Domain/Containers/CommandHandlers/FocusInDirectionHandler.cs

fix: make `FocusInDirectionCommand` a no-op if focused container is maximized

---

GlazeWM.Bar/Components/SystemTrayComponent.xaml

I've noticed that some system tray icons are getting triggered on expand if that icon is right under the expand arrow.
Changing the event trigger to MouseLeftButtonUp fixed the issue.

fix: system tray component expand on mouse button up

---

GlazeWM.App/Resources/sample-config.yaml
GlazeWM.Domain/UserConfigs/GeneralConfig.cs
GlazeWM.Domain/Windows/CommandHandlers/ManageWindowHandler.cs
README.md

Issue: some apps (Autodesk Maya, 3ds Max) have a workflow of creating floating windows constantly. Setting a rule of "set floating" to those windows will center them on the screen every time you open them. By default, those apps keep the position of those windows internally, but GlazeWM will treat them as new windows every time and center them (even within one session).
Solution: have an option to disable initial centering of newly created floating windows. Default behavior will not change, unless the user decides to set the option to false. I keep it constantly to false in my build.
Possible issues: I haven't tested this on a multi-monitor setup, as I don't use multiple screens.
Partially closes the (#436)

feat: option to disable floating windows initial centering

---

GlazeWM.Domain/Containers/CommandHandlers/DetachContainerHandler.cs

Imagine a workspace with three windows.
Closing (detaching) TW1 triggers the following section: 
https://github.com/glazerdesktop/GlazeWM/blob/18eb8c80ceaf166eaf6c74b7a3846871e18db9ae/GlazeWM.Domain/Containers/CommandHandlers/DetachContainerHandler.cs#L70-L80
in this case, `detachedSiblings[0]` refers to the `splitContainer`, and `detachedParent` is the workspace. The `splitContainer` flattens correctly, but then flattening the workspace causes its deletion, directly attaching `TW2` and `TW3` to the monitor.
Then during redrawing, `TW2` and `TW3` can't find their workspace ancestor, leading to the exception `Sequence contains no elements`.
https://github.com/glazerdesktop/GlazeWM/blob/18eb8c80ceaf166eaf6c74b7a3846871e18db9ae/GlazeWM.Domain/Containers/CommandHandlers/RedrawContainersHandler …

fix: workspace shouldn't be flattened

---

.github/actions/release-with-artifacts/action.yaml
README.md

Personally I had some issues with navigation within the README, especially to find what components are currently supported.
While refactoring the README a bit I also noticed that it still contained some old references to the previous project URL.

docs: enhance readme; add table of contents

---

GlazeWM.Domain/Containers/Container.cs

* Correctly handle `Siblings`, `Index`, and `SelfAndSiblings` getters for the `RootContainer`.
Thanks to @maxle5 for figuring out the cause of the crash in #511 🙏 
Closes #518, #510

fix: crash when detaching monitor on display settings change

---

packages/wm/src/workspaces/workspace.rs

The name field is great to have for testing purposes as well as displaying in Zebar etc. Also added is_displayed so we can see which workspaces are active.

feat: extend workspace dto with `name` and `is_displayed` state

---

README.md

Just some minor typo/grammar fixes to allow better readability and understanding

docs: typo and grammar fixes in readme

---

.github/workflows/release.yaml

Related issue #652 
**Important**- this PR and the Winget releaser expects the following prerequisites which only maintainers can do:
- The existence of a `Classic Personal Access Token` (PAT) with `public_repo` scope stored in a variable/secret called `WINGET_TOKEN`
- The existence of a fork of `microsoft/winget-pkgs` under the same account of this repository
The prerequisites above should be done via the Github account of the repo, outside of the PR.

feat: Adding Winget auto releaser, closes #652

---

packages/wm/src/app_command.rs
packages/wm/src/monitors/commands/focus_monitor.rs
packages/wm/src/monitors/commands/mod.rs

This PR is to add a command option to the `focus` command that allows you to focus on a specific monitor by index.
And example usage of this would be:
```
glazewm.exe command focus --monitor 1
```
This would focus on the second monitor.
The indexing is zero-based, so the first monitor would be monitor 0.

feat: Focus command to focus on specific monitor by index

---

packages/wm/src/app_command.rs
packages/wm/src/containers/commands/toggle_tiling_direction.rs

I added the two commands `set-tiling-direction-vertical` and `set-tiling-direction-horizontal`
in order to be able to set the tiling direction faster and in the same way it is done in `i3wm`.
When using `toggle-tiling-direction` one always has to identify the current direction first.
Let me know what you think. Specially whether using `panic!` here is the right method:
https://github.com/JonasWischeropp/glazewm/blob/3c3fd07cd667c7e6165aa422d144e88ee0858af0/packages/wm/src/containers/commands/toggle_tiling_direction.rs#L110
Thank you for this amazing window manager.

feat: add command `set-tiling-direction [vertical|horizontal]`

---

README.md
packages/wm/src/user_config.rs

feat: add support for using env variable `GLAZEWM_CONFIG_PATH` for config path

---

packages/wm/src/common/events/handle_window_focused.rs

fix: ignore focus events from windows that aren't the foreground window

---

README.md
packages/watcher/src/main.rs
packages/wm/src/app_command.rs
packages/wm/src/user_config.rs
packages/wm/src/wm.rs
resources/assets/sample-config.yaml

This PR addresses #650 and #646
I added two config entries that allow easy execution of commands at shutdown and restart similar to `general.startup_commands`.
|Config entry| Execution time|
|-|-|
| `general.shutdown_commands` | just before shutdown |
| `general.reload_commands` | after config has reloaded |
These are then used in the sample config to shutdown and reload Zebar.
```yaml
general:
startup_commands: ['shell-exec %userprofile%/.glzr/zebar/start.bat']
shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
reload_commands: [
'shell-exec taskkill /IM zebar.exe /F',
'shell-exec %userprofile%/.glzr/zebar/start.bat'
]
```

feat: add new config `general.shutdown_commands` and `general.reload_commands` and shutdown/reload Zebar along side the WM

---

packages/wm/src/containers/commands/toggle_tiling_direction.rs
packages/wm/src/monitors/commands/mod.rs
packages/wm/src/user_config.rs

Just fixed the formatting in oder that the git workflow `Lint check` no longer fails.

style: fix formatting

---

packages/wm/src/app_command.rs
packages/wm/src/common/commands/reload_config.rs
packages/wm/src/main.rs
packages/wm/src/wm.rs
resources/assets/sample-config.yaml

* Ensure `shutdown_commands` and `config_reload_commands` are run when corresponding system tray options are clicked.
* Update Zebar launch via `startup_commands` to be compatible with Zebar v2.
* Zebar restart via `taskkill` doesn't seem to be working properly. Removing it for now until a reload CLI command is added natively.

fix: shutdown and config reload commands get run from tray menu

---

packages/wm/src/workspaces/commands/move_workspace_in_direction.rs

* Remove any empty workspaces left over after `move-workspace` command.
Closes #655

fix: remove any empty workspaces after `move-workspace` command

---

.github/workflows/release.yaml
.github/workflows/winget-release.yaml

Changed winget workflow to correctly run as intended during publish of new release

ci: add separate winget release workflow

---

packages/wm/src/common/length_value.rs
packages/wm/src/common/rect_delta.rs
packages/wm/src/containers/traits/tiling_size_getters.rs
packages/wm/src/workspaces/workspace.rs

I was trying to make my zebar config work with multiple monitors that have different display scaling factors.
Related discussion: glzr-io/zebar#72
This PR suggests a possible fix by scaling `outer_gap` and `inner_gap` by the display scale.
Let me know if I should change something.

feat: scale inner and outer gaps by monitor DPI 

---

packages/wm/src/app_command.rs
packages/wm/src/wm_state.rs
packages/wm/src/workspaces/workspace_target.rs

close https://github.com/glzr-io/glazewm/issues/715
usage:
```
- commands: ["focus --next-workspace"] 
bindings: ["Lwin+Right"]
- commands: ["focus --prev-workspace"] 
bindings: ["Lwin+Left"]
- commands: ["focus --next-active-workspace"] 
bindings: ["Lwin+Right"]
- commands: ["focus --prev-acitve-workspace"] 
bindings: ["Lwin+Left"]
```

feat: focus next/prev workspace by config order; add `—next-active-workspace` and `—prev-active-workspace`

---

packages/wm/src/common/events/handle_window_focused.rs

close: https://github.com/glzr-io/glazewm/issues/780
refer to:
https://discord.com/channels/1041662798196908052/1041678923878125589/1296640722035802133

fix: prevent focus requests from being lost from windows on inactive workspaces

---

packages/wm/src/user_config.rs
packages/wm/src/wm_state.rs

To @rpop0  "complaints" I added **not equals** for matchtype.
- Added a new match type: NotEquals, which checks for inequality.
- Extended the Regex match type to support an optional `not` parameter for negating regex matches.
An example of use would be for steam, you want the friend list and the chat to be ignored.
- window_title for friends list is Friends
- window_title for a chat is the person's name.
Normally you can use the regex method ^(?:(?!Steam).*$ but rust does not have support for Negative Lookahead.
Exemple of ussage:
- Not Equals:
```
- window_process: { equals: "steamwebhelper" }
window_title: { not_equals: "Steam" }
```
-Not Regex
```
- window_process: { equals: "steamwebhelper" }
window_title: { regex: "Steam", not: true }
```
At the same time, it fixes #786.

feat: add `not_equals` and `not_regex` match types

---

README.md

Fix the config documentation link in readme

docs: fix link to "Config documentation" heading in readme

---

packages/wm/src/app_command.rs
packages/wm/src/common/commands/shell_exec.rs
packages/wm/src/common/platform/platform.rs

This will allow some terminal commands to be executed without pop-ups, such as powershell,nushell
before：
https://github.com/user-attachments/assets/043783e5-7dfb-4117-973e-5052cfb623d0
apply this pr:
```powershell
- commands: ["shell-exec --hide-window nu ~/script/clash.nu"]
bindings: ["Ctrl+Enter"]
```
https://github.com/user-attachments/assets/3c2000fd-e02e-41e0-baad-96985add4e78

feat: add `--hide-window` flag to allow `shell-exec` to run commands in background

---

packages/wm/src/common/platform/platform.rs

When switching to an empty workspace, we should logically focus on the desktop window, but in practice it fails, leaving us in a state where no window is focused, resulting in some window-event-based applications working abnormally, such as ahk:
desktop windows focus fail:
the windows message catch tool message: "can't get any focus window"
https://github.com/user-attachments/assets/9595f96c-398f-4c26-bfcd-e9fd292e87da
apply this pr:
https://github.com/user-attachments/assets/dd426f36-6e73-420d-9803-3f9304c78dd6

fix: set focus to valid desktop window in an empty workspace

---

packages/wm/Cargo.toml

The project cannot be cross-compiled on Linux, because the file paths are in a format which is supported by Windows only:
```toml
[lib]
path = "src\\lib.rs"
[[bin]]
name = "glazewm"
path = "src\\main.rs"
```
Changing `\\` to `/` fixes the issue and works both, on Linux and on Windows.
Motivation: My whole developer workflow is on WSL. My typical workflow is to build on WSL and then test on Windows.
(assuming this patch is applied and nightly is setup already)
1. Install dependencies: `sudo apt-get update; sudo apt-get install libgtk-3-dev librust-atk-dev`
2. Add windows (gnu) target: `rustup target add x86_64-pc-windows-gnu`
3. Finally, build the project: ` cargo build --target x86_64-pc-windows-gnu`

fix: change cargo lib and bin path to enable build on WSL

---

packages/wm/src/common/platform/platform.rs

Fixes issue where the `set_window_animations_enabled` and `window_animations_enabled` were not always working properly, required the `uiParam` to be the `cbSize` along with persisting the changed state with `SPIF_UPDATEINIFILE` & `SPIF_SENDCHANGE`.
https://github.com/glzr-io/glazewm/pull/818#issuecomment-2456631532

fix: persist window animations setting across restarts

---

packages/wm/src/app_command.rs
packages/wm/src/user_config.rs
packages/wm/src/windows/commands/mod.rs
packages/wm/src/windows/commands/set_window_position.rs

This pr allows you to set size,position and centered status of the window when setting it to float, so that the launch size,position and center can be specified in the window open rule

feat: add new `position` command; allow size and position to be set with `set-floating` command

---

packages/wm/src/common/platform/native_window.rs

Regression found by @DreamMaoMao in #792
https://github.com/user-attachments/assets/c167e9e4-b85c-4d09-83bd-1d613ac73145

fix: window positioning regression when windows are opened simultaneously

---

packages/wm/src/common/commands/platform_sync.rs
packages/wm/src/common/commands/toggle_pause.rs
packages/wm/src/common/events/handle_window_moved_or_resized_end.rs
packages/wm/src/common/platform/event_listener.rs
packages/wm/src/common/platform/event_window.rs
packages/wm/src/common/platform/keyboard_hook.rs
packages/wm/src/ipc_server.rs
packages/wm/src/main.rs
packages/wm/src/wm.rs
packages/wm/src/wm_event.rs
packages/wm/src/wm_state.rs

Small follow-up to #828 @michidk

fix: ignore resize events and skip IPC emissions while WM is paused

---

resources/assets/sample-config.yaml

Notice many people asking how this key is bound, and it is a common feature, so suggest adding them to the default sample configuration

feat: revert to keybindings for prev/next active workspace in sample config

---

packages/wm/src/workspaces/commands/move_workspace_in_direction.rs

fix: `move-workspace` moves cursor if `cursor_jump` is enabled

---

packages/wm/src/wm_state.rs

Fixes the pause IPC not working:
```sh
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Arch\home\michi\dev\glazewm\target\x86_64-pc-windows-gnu\debug> ./glazewm sub -e pause_changed
{"data":{"eventType":"pause_changed","isPaused":false},"error":null,"subscriptionId":"bf8e2089-487a-4cc9-8846-f5c9e7b17b82","success":true}
{"data":{"eventType":"pause_changed","isPaused":false},"error":null,"subscriptionId":"bf8e2089-487a-4cc9-8846-f5c9e7b17b82","success":true}
{"data":{"eventType":"pause_changed","isPaused":false},"error":null,"subscriptionId":"bf8e2089-487a-4cc9-8846-f5c9e7b17b82","success":true}
```

fix: pause IPC event not emitting

---

.vscode/settings.json
packages/wm-platform/src/event_window.rs
packages/wm-platform/src/native_window.rs
packages/wm/src/commands/general/platform_sync.rs
packages/wm/src/commands/window/move_window_in_direction.rs
packages/wm/src/commands/window/move_window_to_workspace.rs
packages/wm/src/events/handle_window_shown.rs
packages/wm/src/main.rs
packages/wm/src/wm.rs

This PR adds a settings.json file in the .vscode folder. This will make all VS Code users automatically get the correct indentation settings for this project and use clippy as their rust-analyzer check command, as mentioned in https://github.com/glzr-io/glazewm/blob/main/CONTRIBUTING.md#tips .

chore: add vscode settings

---

packages/wm-common/src/app_command.rs
packages/wm/src/models/workspace_target.rs
packages/wm/src/wm.rs
packages/wm/src/wm_state.rs

close #938 
Also added `NextActiveInMonitor` and `PreviousActiveInMonitor` to `WorkspaceTarget` and their respective implementations.

feat: add `--next-active-workspace-on-monitor` and `--prev-active-workspace-on-monitor` to `focus` and `move` commands

---

packages/wm-platform/src/platform.rs
packages/wm/src/events/handle_mouse_move.rs
packages/wm/src/events/handle_window_focused.rs
packages/wm/src/wm_state.rs

This PR makes the general.focus_follows_cursor code focus the monitor that the cursor is on when there isn't a window to focus. This makes it so if you focus monitor 1, move your cursor to monitor 2 and open a program, the program will open on monitor 2 and not on monitor 1.
Before:
https://github.com/user-attachments/assets/bd260c32-8add-442c-b518-0e5a4ff14aa9
After:
https://github.com/user-attachments/assets/22ce7026-f1fb-43ee-8a92-85125c3127a3
This has been annoying me for a while, so I decided to fix it...
I don't know if it would've been better to make it focus the workspace under the cursor or not. Since there can only be one workspace displayed per monitor, I chose to make it focus the monitor.
Just let me know if you think it would be better to focus the workspace instead!

feat: change monitor focus with `general.focus_follows_cursor`

---

README.md

The old [GLA-ALT](https://github.com/ParasiteDelta/GAT-GWM) repo for auto-tiling was archived then made private. This fork seems to have the [last commit](https://github.com/Dutch-Raptor/GAT-GWM/commit/b76822bd0da1fb7ab685beb5663c8cded535ab6b) from the old repo ([archived version](https://web.archive.org/web/20241112231905/https://github.com/ParasiteDelta/GAT-GWM)) and has some additional improvements made as well. Note that the repo was renamed to GAT-GWM by the original dev as can be seen in the archived link above.

docs: replace GLA-ALT with maintained fork in readme

---

packages/wm/src/commands/monitor/add_monitor.rs
packages/wm/src/user_config.rs

Initializes keep_alive workspaces.  Previous workaround was focusing each of the workspaces manually or using startup commands like this:
```
startup_commands: 
- shell-exec zebar
- move --workspace 2
- move --workspace 3
- move --workspace 4
- move --workspace 5
- move --workspace 6
- move --workspace 7
- move --workspace 8
- move --workspace 1

feat: activate `keep_alive` workspaces on their bound monitor

---

packages/wm/src/events/handle_window_focused.rs

Before: 
https://github.com/user-attachments/assets/601242bc-0047-442a-9796-570d8357b109
After:
https://github.com/user-attachments/assets/a9068f34-89a9-4ba6-9bbe-7dbc867a5d84

fix: broadcast focus change events when focus is manually changed
